@startuml
title Phase2 カテゴリー一覧
!include ./color_setting.pu

participant CategoryListServlet as servlet
participant categorylist.jsp as jsp

->servlet:home.jspから遷移
activate servlet
servlet->jsp:フォワード
deactivate servlet
activate jsp
jsp->:homuButton押下でHomeServletへ遷移
deactivate jsp


@enduml