@startuml

title Phase2 注文編集画面
skinparam defaulttextalignment center

start

floating note left
  【変数の定義】
  ・オーダーの個数：x (1<=x<=4)
  ・トッピングの個数：y (1<=y<=4)
  ・トッピングの総数：z (1=<z<=4)
end note

repeat:画面を表示する;


switch (ユーザーがいずれかのボタンを押す)

case( 注文のマイナスボタン)
if (2<=x<=4) then (正しい場合)
:注文個数を1減らす;
endif

case( 注文のプラスボタン)
if (1<=x<=3) then (正しい場合)
:注文個数を1増やす;
endif

case(トッピングのマイナスボタン)
if (2<=y<=4\nand\n2<=z<=4) then (正しい場合)
:トッピング個数を１減らす;
end if

case(トッピングのプラスボタン)
if (1<=y<=3\nand\n1<=z<=3) then (正しい場合)
:トッピング個数を１増やす;
endif

case( 注文取り消しボタン)
if (ポップアップ表示) then (はいボタン)
:注文を取り消す;
:注文管理画面に遷移;
stop
else (いいえボタン)
:ポップアップを消す;
endif

case( 変更ボタン)

if (ポップアップ表示) then (はいボタン)
:注文の変更を適用;
:注文管理画面に遷移;
stop
else (いいえボタン)
:ポップアップを消す;
endif

case( 一覧に戻るボタン)
:注文管理画面に遷移;
stop

case( ホームボタン)
:ホーム画面に遷移;
stop

endswitch

@enduml