@startuml

title Phase2 ホーム画面

start
repeat:ホーム画面を表示;
switch (ユーザーがボタンを押下)

case ( ログアウトボタン)
if (ポップアップ表示) then (はいボタン)
:login画面に遷移;
stop
else (いいえボタン)
:ポップアップを消す;
end if

case ( 注文管理画面)
    :注文管理画面へ遷移;
stop
case ( 商品一覧ボタン)
    :商品一覧画面へ遷移;
stop
case ( トッピング一覧ボタン)
    :トッピング一覧画面へ遷移;
stop
case ( カテゴリー一覧ボタン)
    :カテゴリー一覧画面へ遷移;
stop
endswitch


@enduml