@startuml

!include ./color_setting.pu

title Phase2 Home、ホーム画面

participant login.jsp
participant HomeServlet
participant home.jsp


activate login.jsp
login.jsp->HomeServlet : 画面遷移
deactivate login.jsp
activate HomeServlet
HomeServlet->home.jsp :フォワード
activate home.jsp
home.jsp->:logOutButton押下でログイン画面へ遷移
home.jsp->:orderManegementButton押下で注文管理画面へ遷移
home.jsp->:productButton押下で商品一覧画面へ遷移
home.jsp->:toppingButton押下でトッピング一覧画面へ遷移
home.jsp->:categoryButton押下でカテゴリ一覧画面へ遷移

deactivate home.jsp
deactivate HomeServlet 
@enduml