@startuml

!include ./color_setting.pu

title Phase2 ordermanegement.jsp、注文管理画面

participant Home.jsp
participant OrderManegementServlet
participant OrderManegementDAO
database "データベース" as DB #red
participant OrderManegementInfo
participant orderManegement.jsp

activate Home.jsp
Home.jsp->OrderManegementServlet:画面遷移
deactivate Home.jsp

activate OrderManegementServlet
OrderManegementServlet->OrderManegementDAO:findAllOrder()
activate OrderManegementDAO
OrderManegementDAO->DB:order_details,multiple_topping,topping
activate DB
DB-->OrderManegementDAO:全部渡す
deactivate DB
OrderManegementDAO->OrderManegementInfo:
activate OrderManegementInfo
OrderManegementInfo-->OrderManegementDAO:orderManegementList
deactivate OrderManegementInfo
OrderManegementDAO-->OrderManegementServlet:orderManegementListをセッションスコープで送る
deactivate OrderManegementDAO
OrderManegementServlet->orderManegement.jsp:ListをJSPに送る

activate orderManegement.jsp
orderManegement.jsp->OrderManegementServlet:severdButtonを押下
OrderManegementServlet->OrderManegementDAO:UpDateProvidedFlag(orderId)
activate OrderManegementDAO
OrderManegementDAO->DB:order_details
activate DB
deactivate OrderManegementDAO
deactivate DB
OrderManegementServlet-->orderManegement.jsp:更新したデータを送る
deactivate OrderManegementServlet
orderManegement.jsp->:historyButtonを押下ServidHistoryServletへ遷移
orderManegement.jsp->:editButtonを押下EditOrderServletへ遷移


@enduml




