@startuml

title Phase2 商品一覧画面 

start

repeat

:選択しているカテゴリの商品リスト表示;
switch (userが商品にあるボタンを押下)

case ( カテゴリボタン)
    :任意のカテゴリを選択;
    

case ( 編集ボタン)
    :商品編集画面へ遷移;
    stop


case (\n スウィッチボタン)
    if (スウィッチボタンの状態) then (オン)

        :商品を表示状態に変更;
    else (オフ)
        :商品を非表示状態に変更;

    endif


case ( 削除ボタン)
    if (ポップアップ表示) then (はいボタン)
        :商品を削除状態に変更;
    else (いいえボタン\n)
    endif 


case ( ホームボタン)
    :ホーム画面へ遷移;
    stop


endswitch



@enduml