@startuml
title Phase2　商品新規作成・編集画面

start

:画面を表示する;
repeat

switch(各種イベント実行)

case( カテゴリ選択)
:プルダウンメニューの中から選ぶ;

case( 商品名記入)
:文字を入力する;

case( トッピング選択)
:選択させたいトッピングにチェックを入れる;

case( 金額入力)
:商品の金額を入力する;

case(   商品一覧へ戻るボタン)
:商品一覧に遷移する;
stop

case( 作成・変更ボタン)
if (カテゴリー選択されている and\n商品名が記入されている and\n金額が入力されている) then(はい)
if(確認のポップアップ表示) then (はいボタン)
:記入内容を適用する;
:商品一覧画面に遷移する;
stop
else(いいえボタン)
:ポップアップを閉じる;
endif
else(いいえ)
:エラーメッセージを表示する;
endif


case( ホームボタン)
:ホーム画面に遷移する;
stop
@enduml