@startuml
title Phase2　トッピング新規作成・編集画面

start

repeat:画面を表示する;

switch(各種イベント実行)

case( トッピング名記入)
:文字を入力する;

case( 金額入力)
:商品の金額を入力する;

case( トッピング一覧へ戻るボタン)
:トッピング一覧画面に遷移する;
stop

case( 作成・変更ボタン)
if (トッピング名が記入されている and\n金額が入力されている) then(はい)
if(確認のポップアップ表示) then (はいボタン)
:記入内容を適用する;
:商品一覧画面に遷移する;
stop
else(いいえボタン)
:ポップアップを閉じる;
endif
else(いいえ)
:エラーメッセージを表示する;
endif

case( ホームボタン)
:ホーム画面に遷移する;
stop
@enduml