@startuml

title Phase2 トッピング画面 

start

repeat:トッピングリスト表示;
switch (ユーザーがトッピングにあるボタンを押下)

case ( 編集ボタン)
    :トッピング編集画面へ遷移;
    stop


case (\n スウィッチボタン)
    if (スウィッチボタンの状態) then (オン)

        :トッピングを表示状態に変更;
    else (オフ)
        :トッピングを非表示状態に変更;

    endif


case ( 削除ボタン)
    if (ポップアップ表示) then (はいボタン)
        :トッピングを削除状態に変更;
    else (いいえボタン)
    endif


case ( ホームボタン)
    :ホーム画面へ遷移;
    stop


endswitch



@enduml